### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Denisolt**
Crucial readme update

### CODE REVIEW

**Comment by aarora08** [comment]
Please add proper description and title to your PR

**Review by aarora08 — APPROVED** [review]

**Comment by Denisolt** [comment]
> Please add proper description and title to your PR

Thank you for pointing it out. Can we make a PR template for the future?

**Comment by aarora08** [comment]
> > Please add proper description and title to your PR
> 
> Thank you for pointing it out. We can make a PR template for the future?

Yes, we can use one from here [PR Templates for Github](https://github.com/stevemao/github-issue-templates)

**Comment by Denisolt** [comment]
> > > Please add proper description and title to your PR
> > 
> > 
> > Thank you for pointing it out. We can make a PR template for the future?
> 
> Yes, we can use one from here [PR Templates for Github](https://github.com/stevemao/github-issue-templates)

@aarora08 What about CI/CD? Any thoughts on that? We would like to automate the flow as much as possible.

**Pull request closed without merging**
